name: build-docker-image

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Docker image tag, e.g. 2.1'
        required: true
        type: string
      lsky_version:
        description: 'Version of lsky-pro'
        required: true
        type: string

env:
  IMAGE: ${{ vars.IMAGE }}:${{ inputs.image_tag }}
  LSKY_VERSION: ${{ inputs.image_tag }}

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Prepare
        run: sed -i 's/LSKY_VERSION_CHANGE_ME/$LSKY_VERSION/g' Dockerfile

      - name: Build docker image
        run: |
          docker build -t ${IMAGE} .
          docker tag ${IMAGE} ${{ vars.IMAGE }}:latest

      - name: List docker image
        run: docker image ls

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push to DockerHub
        run: |
          docker push ${IMAG}
          docker push ${{ vars.IMAGE }}:latest
